// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTWcOlOS174LJrmyCx-qqW3eRAkAZdSS8',
    appId: '1:480027131319:web:6b6105c483a1866685bc32',
    messagingSenderId: '480027131319',
    projectId: 'brokecheck-90123',
    authDomain: 'brokecheck-90123.firebaseapp.com',
    storageBucket: 'brokecheck-90123.firebasestorage.app',
    measurementId: 'G-DY7WSRFBGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUf-og_oMNe_vRwhXYDdJrulCmbtuj_Ko',
    appId: '1:480027131319:android:68144648178cfba885bc32',
    messagingSenderId: '480027131319',
    projectId: 'brokecheck-90123',
    storageBucket: 'brokecheck-90123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJN39GdN1zD1rHGX5Nyyy0b2Upc_oT4Ig',
    appId: '1:480027131319:ios:fe50daa8c110f5a785bc32',
    messagingSenderId: '480027131319',
    projectId: 'brokecheck-90123',
    storageBucket: 'brokecheck-90123.firebasestorage.app',
    iosBundleId: 'com.example.brokecheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJN39GdN1zD1rHGX5Nyyy0b2Upc_oT4Ig',
    appId: '1:480027131319:ios:fe50daa8c110f5a785bc32',
    messagingSenderId: '480027131319',
    projectId: 'brokecheck-90123',
    storageBucket: 'brokecheck-90123.firebasestorage.app',
    iosBundleId: 'com.example.brokecheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTWcOlOS174LJrmyCx-qqW3eRAkAZdSS8',
    appId: '1:480027131319:web:4ae9f63d7675022d85bc32',
    messagingSenderId: '480027131319',
    projectId: 'brokecheck-90123',
    authDomain: 'brokecheck-90123.firebaseapp.com',
    storageBucket: 'brokecheck-90123.firebasestorage.app',
    measurementId: 'G-JW5777DJYW',
  );

}